Coddin\OpenIDConnect\Domain\OAuthRedirectUri:
  type: entity
  table: oauth_redirect_uri
  repositoryClass: Coddin\OpenIDConnect\Domain\Repository\OAuthRedirectUriRepository
  id:
    id:
      type: integer
      options:
        unsigned: true
      generator:
        strategy: AUTO
  fields:
    uri:
      type: string
  manyToOne:
    oAuthClient:
      targetEntity: OAuthClient
      inversedBy: redirectUris
      joinColumn:
        name: oauth_client_id
      referencedColumnName: id
